### ISSUE TITLE
Write test for the similarity calculation.

### ISSUE THREAD

**Issue by KeitaW** [KeitaW/spikesim#1]
- [ ]  Create a branch for this issue.
- [ ]  Copy `https://github.com/KeitaW/Chaldea/blob/master/chaldea/edit_sim.jl` to this repo.
- [ ]  Write tests based on `edt_sim.jl`.
- [x]  Write a draft function using numpy
- [x]  Write a faster-version using Cython

**Comment by tuanpham96** [comment]
Hi, this is an interesting method. I am trying it on a set of data and I was wondering if you have plans to include detection/extraction of sequences; or do you have any suggestion of the approach? 
 
I have plotting out the windows which belong to the same cluster, along with the spikes of those windows but they do not seem to match well with each other, nor with the cluster profiles in `es.profiles`. Do you have any suggestion?
