### ISSUE TITLE
Missing dependency? (hdbscan)

### ISSUE THREAD

**Issue by milenamc** [KeitaW/spikesim#16]
I tried to import `editsim` using the following expression:

`from spykesim import editsim`

and `hdbscan` was requested, even though previous dependency checks were successful. Maybe it should be added to the dependency list?

System info:

```
Python 3.7.4 (default, Jul 16 2019, 07:12:58)
[GCC 9.1.0] on linux
```
```
Linux 5.2.9-arch1-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux
```

**Comment by KeitaW** [comment]
That's true. Thanks! 
This has been addressed in https://github.com/KeitaW/spykesim/pull/21.
